language: node_js
node_js:
  - "9"

before_install:
  - npm install -g @vue/cli

cache: npm

script:
  - "npm install --save-dev"
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./dist
  on:
    branch: master