language: node_js
node_js:
  - "9"

before_install:
  - npm run build

cache: npm

script:
  - cd src
  - npm install
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./public
  on:
    branch: master